config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  devise_for :users
  # get 'albums/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :albums
  delete "images/:id/purge", to: "albums#purge", as: "purge_image"
end

app/models/album.rb
class Album < ApplicationRecord
    validates :title, :description, :cover_image, :all_tags,:images, presence: true
    has_one_attached :cover_image
    has_many_attached :images
    has_and_belongs_to_many :tags
    belongs_to :user

    def all_tags=(names)
        self.tags = names.split(',').map do |name|
            Tag.where(name: name.strip).first_or_create!
        end
    end
    def all_tags
        tags.map(&:name).join(", ")
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :albums
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :albums
end

app/controllers/albums_controller.rb
  class AlbumsController < ApplicationController
    before_action :authenticate_user!
    def index
      @albums = current_user.albums
    end

    def show
      @album=Album.find(params[:id])
    end

    def new 
      @album=Album.new
    end
  
    def create
      @album = current_user.albums.new(album_params)
      if @album.save
        MessageMailer.index.deliver_now
        # NotificationMailer.album_notification(current_user.email).deliver_now if @album.published?
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @album = Album.find(params[:id])
    end

    def update
      @album = Album.find(params[:id])

      if @album.update(album_params)
        redirect_to root_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @album = Album.find(params[:id])
      @album.destroy
      redirect_to root_path, status: :see_other
    end

    def purge
      # album = Album.find(params[:id])
      attachment = ActiveStorage::Attachment.find(params[:attachment_id])
      attachment.purge
      redirect_to root_path
    end 

    private
      def album_params
        params.require(:album).permit(:title, :description, :all_tags, :published, :cover_image, :images=> [])
      end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @albums = current_user.albums
      redirect_to :albums
    else
      @albums = Album.where(published: true)
    end
    @q = @albums.ransack(params[:q])
    @albums = @q.result
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_form.html.erb
<div class="container">
<%= form_with model: album do |form| %>
  <div>
    <%= form.label :title,class:"form-group" %>
    <%= form.text_field :title,class:"form-control" %>
    <% album.errors.full_messages_for(:title).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description,class:"form-group" %>
    <%= form.text_area :description,class:"form-control" %>
    <% album.errors.full_messages_for(:description).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div>
    <div>
    <%= form.label :tag, class:"form-group" %>
    <%= form.text_field :all_tags, class:"form-control" %>
    <% album.errors.full_messages_for(:all_tags).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :cover_image,class:"form-group" %>
    <%= form.file_field :cover_image,class:"form-control" %>
    <% album.errors.full_messages_for(:cover_image).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :images,class:"form-group" %><br>
    <%= form.file_field :images,class:"form-control", :multiple => true %>
    <% album.errors.full_messages_for(:images).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div>
  <div class="field">
    <%= form.check_box :published, {}, true, false%> 
    <%= form.label "Published"%>
  </div><br>
  <div>
    <%= form.submit %>
  </div>
<% end %>


</div>

app/views/albums/edit.html.erb
<div class="col-lg-8">
    <h1>Edit Album</h1>
    <%= render "form", album: @album %>
</div>

app/views/albums/index.html.erb
<div class="color">
<h1 class="text-center">Here You Can View Albums</h1><br>
<div class="container">
<div class="row">
  <% @albums.each do |album| %>
    <div class="col-md-4">
      <div class="card mt-2 bg-light">
        <div class="card-header">
          <div class="text-center"> 
            <strong>Title:</strong>
            <%=album.title%>
          </div>
        </div>
        <div class="card-body text-center"style="height:17rem;">
          <% if album.cover_image.attached? %>
            <%= link_to album do%>
              <%=image_tag(album.cover_image,style:"width:100%")%>
            <%end%>
          <%end%>
        </div>
        <div class="card-footer mb-2">
          <div class="text-center">
            <strong>Tag:</strong>
             <%=album.all_tags%>
          </div>
         <div class="text-center">
          <strong>Total Images: </strong>
           <%=album.images.count%>
        </div>
       <div class="text-center">
          <strong>Description:</strong>
           <%=album.description%>
        </div>
        <div class="text-center">
          <strong>Created at :</strong>
           <%=album.created_at.time %>
        </div>
        </div>
        <span class="text-center mb-3">
        <%= link_to "Edit" , edit_album_path(album), class:" btn btn-info" %>
        <%= link_to "Delete" , album_path(album) , method: :delete, data: {confirm: 'Are you Sure?' }, class:" btn btn-danger" %>
        <span>
      </div>
    </div>
    <%end%>
  </div>
</div>
</div>

app/views/albums/new.html.erb
<div class="container">
    <h1>New Album</h1>
    <%= render "form", album:@album %>
</div>

app/views/albums/show.html.erb
<div class="container">
  <div class="row">
    <% @album.images.each do |image|%>
      <div class="col">
        <div class="card-body">
          <%= link_to image,target:"_blank" do%>
            <%= image_tag(image)%>
              <div>
                    <%= link_to "Destroy", purge_image_path(attachment_id: image.id), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  },class:"btn btn-danger ms-1 mt-2"%></li>
                </div>
          <%  end %>
        </div>
      </div>
    <%  end %>
  </div>
</div>

app/views/home/index.html.erb
<%# body start %>
  <%= search_form_for @q, url: root_path do |f| %>
    <div class="form-group text-center">
      <%= f.search_field :tags_name_eq ,placeholder:'search by tag' %>
      <%= f.submit %>
    </div>
  <%end%>
<br>
<h1 class="text-center mt-3">Here You Can View Published Albums</h1><br>
<div class="container">
<div class="row">
  <% @albums.each do |album| %>
      <div class="col-md-4">
        <div class="card mt-4">
          <div class="card-header">
            <div class="text-center"> 
              <strong>Title:</strong>
              <%=album.title%>
            </div>
          </div>
          <div class="card-body text-center"style="height:17rem;">
            <% if album.cover_image.attached? %>
                <%= image_tag(album.cover_image,style:"width:100%")%>
            <%end%>
          </div>
          <div class="card-footer">
          <div class="text-center">
          <strong>Tag:</strong>
           <%= album.all_tags%>
        </div>
        <div class="text-center">
            <strong>Description:</strong>
            <%=album.description%>
          </div>
          <div class="text-center">
            <strong>Total Images: </strong>
            <%=album.images.count%>
          </div>
          <div class="text-center">
            <strong>Created at :</strong>
            <%=album.created_at.time %>
          </div>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>  
<%# body end %>

app/views/layouts/_footer.html.erb
<%# footer start %>
<br><br><br>
<div class="container-fluid bg-dark"style="position:fixed;left:0px;bottom:0px;height:7rem; margin-top:300px;">
<footer class="py-3 my-4 mb-0">
<ul class="nav justify-content-center border-bottom pb-3 mb-3">
<% if user_signed_in?%>
  <li class="me-2 nav-link px-2 text-muted "><%= link_to "Home", root_path, class:"btn btn-success" %></li>
  <%else%>
  <li class="me-2 nav-link px-2 text-muted"><%= link_to "Home", root_path, class:" btn btn-success" %></li>
<%end%>    
  <li class="me-1 nav-link px-2 text-muted"><%= link_to "Create Album", new_album_path, class:"btn btn-primary" %></button></li>
</ul>
<p class="text-center text-muted">&copy; 2021 Company, Inc</p>
</footer>
</div>
<%# footer end %>

app/views/layouts/_header.html.erb
<%# header start %>
<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
       <% if user_signed_in?%>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center">
          <li><%= link_to "Home", root_path, class:"btn btn-info me-2" %></li>
          <li><%= link_to "Create Album", new_album_path, class:"btn btn-danger" %></li>          
        </ul>
        <%else%>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <%= link_to "Home", root_path, class:"btn btn-primary me-2" %>
        </ul>
        <%end%>
        <div class="text-end">
        <% if user_signed_in? %>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <p>Email: <%= current_user.email%></p>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-success mb-2 ms-2" %>
        </ul>  
        <% else %>
          <%= link_to "Sign Up",  new_user_registration_path, class:"btn btn-info me-2" %>
          <%= link_to "Sign In",  new_user_session_path, class:"btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </header>
<%# header end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>
  <body class="color">
    <%= render "layouts/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <%= yield %>
  <%= render "layouts/footer" %>
  </body>
</html>